error_handling:
  required: true

max_warnings: 5
max_violations: 2

hardcoding:
  detect_secrets: true
  message: "Do not hardcode sensitive information. Use environment variables or a configuration file."

commented_code:
  allow_comment_blocks: false
  message: "Remove unnecessary commented-out code for better readability."

import_order:
  order:
    - standard
    - third_party
    - project_specific
  message: "Follow import order: standard > third-party > project-specific imports."

indentation:
  spaces_per_indent: 4
  message: "Use 4 spaces per indentation level."

naming_convention:
  function_names: "^[a-z_]+$"
  variable_names: "^[a-z_]+$"
  message: "Use snake_case for function and variable names."

notebook_specific_rules:
  dbutils_commands: true
  spark_conf_set: true
  message: "Follow best practices for Databricks notebook-specific commands."
